/**
 * @module @spark-appworks/spark-component:components/fields/data-components/index
 * 职责：作为 data-components（未注册组件类型）目录的公开导出入口，汇聚渲染器、props、类型和 zero-code 能力。
 * 边界：只维护 field-level/data-field 的模块出口，不新增业务行为，也不绕过具体实现文件的契约。
 * AI用途：需要发现 data components 对外暴露哪些子模块时，从本模块进入，再跳到具体 props、Vue 或 zero-code 文件。
 */
export { default as FieldText } from './text/FieldText/FieldText.vue'
export { default as FieldTextarea } from './text/FieldTextarea/FieldTextarea.vue'
export { default as FieldHtmlEditor } from './text/FieldHtmlEditor/FieldHtmlEditor.vue'
export { default as FieldNumber } from './value/FieldNumber/FieldNumber.vue'
export { default as FieldDate } from './datetime/FieldDate/FieldDate.vue'
export { default as FieldSelect } from './choice/FieldSelect/FieldSelect.vue'
export { default as FieldMultiSelect } from './choice/FieldMultiSelect/FieldMultiSelect.vue'
export { default as FieldRadio } from './choice/FieldRadio/FieldRadio.vue'
export { default as FieldCheckbox } from './choice/FieldCheckbox/FieldCheckbox.vue'
export { default as FieldCheckboxGroup } from './choice/FieldCheckboxGroup/FieldCheckboxGroup.vue'
export { default as FieldSwitch } from './value/FieldSwitch/FieldSwitch.vue'
export { default as FieldSlider } from './value/FieldSlider/FieldSlider.vue'
export { default as FieldRate } from './value/FieldRate/FieldRate.vue'
export { default as FieldColor } from './value/FieldColor/FieldColor.vue'
export { default as FieldIcon } from './value/FieldIcon/FieldIcon.vue'
export { default as FieldImage } from './file/FieldImage/FieldImage.vue'
export { default as FieldFilePath } from './file/FieldFilePath/FieldFilePath.vue'
export { default as FieldFileBrowser } from './file/FieldFileBrowser/FieldFileBrowser.vue'
export { default as FieldUpload } from './file/FieldUpload/FieldUpload.vue'
export { default as FieldEntityPicker } from './picker/FieldEntityPicker/FieldEntityPicker.vue'
export { default as FieldUserPicker } from './picker/FieldUserPicker/FieldUserPicker.vue'
export { default as FieldDeptPicker } from './picker/FieldDeptPicker/FieldDeptPicker.vue'
export { default as FieldProductPicker } from './picker/FieldProductPicker/FieldProductPicker.vue'
export { default as FieldCascader } from './picker/FieldCascader/FieldCascader.vue'
export { default as FieldTreeSelect } from './picker/FieldTreeSelect/FieldTreeSelect.vue'
export { default as FieldTransfer } from './picker/FieldTransfer/FieldTransfer.vue'
export { default as FieldSegmented } from './choice/FieldSegmented/FieldSegmented.vue'
export { default as FieldCheckTag } from './choice/FieldCheckTag/FieldCheckTag.vue'
export { default as FieldMention } from './text/FieldMention/FieldMention.vue'
export { default as FieldTimePicker } from './datetime/FieldTimePicker/FieldTimePicker.vue'
export { default as FieldTimeSelect } from './datetime/FieldTimeSelect/FieldTimeSelect.vue'
export { default as FieldAutocomplete } from './text/FieldAutocomplete/FieldAutocomplete.vue'

// ── Props 类型 ──
export type { RTextProps } from './text/FieldText/FieldText.props'
export type { RTextareaProps } from './text/FieldTextarea/FieldTextarea.props'
export type { RHtmlEditorProps } from './text/FieldHtmlEditor/FieldHtmlEditor.props'
export type { RNumberProps } from './value/FieldNumber/FieldNumber.props'
export type { RDateProps, DatePickerType } from './datetime/FieldDate/FieldDate.props'
export type { RSelectProps } from './choice/FieldSelect/FieldSelect.props'
export type { RMultiSelectProps, MultiValue } from './choice/FieldMultiSelect/FieldMultiSelect.props'
export type { RRadioProps } from './choice/FieldRadio/FieldRadio.props'
export type { RCheckboxProps } from './choice/FieldCheckbox/FieldCheckbox.props'
export type { RCheckboxGroupProps, CheckboxGroupMultiValue } from './choice/FieldCheckboxGroup/FieldCheckboxGroup.props'
export type { RSwitchProps } from './value/FieldSwitch/FieldSwitch.props'
export type { RSliderProps } from './value/FieldSlider/FieldSlider.props'
export type { RRateProps } from './value/FieldRate/FieldRate.props'
export type { RColorProps } from './value/FieldColor/FieldColor.props'
export type { RIconProps } from './value/FieldIcon/FieldIcon.props'
export type { RImageProps } from './file/FieldImage/FieldImage.props'
export type { RFilePathProps } from './file/FieldFilePath/FieldFilePath.props'
export type { RFileBrowserProps } from './file/FieldFileBrowser/FieldFileBrowser.props'
export type { RUploadProps } from './file/FieldUpload/FieldUpload.props'
export type { REntityPickerProps } from './picker/FieldEntityPicker/FieldEntityPicker.props'
export type { RCascaderProps, CascaderPath, CascaderValue } from './picker/FieldCascader/FieldCascader.props'
export type { RTreeSelectProps } from './picker/FieldTreeSelect/FieldTreeSelect.props'
export type { RTransferProps, TransferValue } from './picker/FieldTransfer/FieldTransfer.props'
export type { RSegmentedProps } from './choice/FieldSegmented/FieldSegmented.props'
export type { RCheckTagProps } from './choice/FieldCheckTag/FieldCheckTag.props'
export type { RMentionProps } from './text/FieldMention/FieldMention.props'
export type { RTimePickerProps } from './datetime/FieldTimePicker/FieldTimePicker.props'
export type { RTimeSelectProps } from './datetime/FieldTimeSelect/FieldTimeSelect.props'
export type { RAutocompleteProps, FetchSuggestionsCallback } from './text/FieldAutocomplete/FieldAutocomplete.props'
